name: Demo workflow
on: workflow_dispatch
jobs: 
  demo:
    runs-on: ubuntu-latest
    steps:
        - name: Lets greet each other
          run: echo " Hello ITA members!"
        - name: See you soon
          run: echo " Bye Bye"
  demo2:
    runs-on: ubuntu-latest
    needs: demo
    steps:
        - name: Lets do it again here
          run: |
              echo "Hi again ITA members"
              echo "How are you all doing"
              echo "See you again"
  
